### ISSUE TITLE
Commands/Console

### ISSUE THREAD

**Issue by fstinner** [RWTH-EBC/EBC-Tutorials#1]
How do you reach console the easiest way? (I.e. to get the correct folder in console) This is not described in the 101.

I tried "Open enhanced console here" from Python and it worked well with git. But it's not cmd.

**Comment by marcusfuchs** [comment]
One easy way in Windows 7 is to 
- Click on the Windows symbol on your task bar
- Focus the search field
- Type `cmd`
- Press enter

Does this not work on your system or is this not what you meant?

**Comment by fstinner** [comment]
@PRemmen provided a good response:
- shift+right-click
- click on `Eingabeaufforderung hier öffnen`

I try to extend the tutorial with this small part.
When you choose only `cmd`, you have to search your git path with `cd`.
