### ISSUE TITLE
Mistakes or lack of clarity in git tutorial

### ISSUE THREAD

**Issue by aku-cbe** [RWTH-EBC/EBC-Tutorials#11]
I read through the git tutorial and was supposed to mention mistakes or passages with a certain lack of clarity.
first: spelling mistakes.
![spelling mistakes](https://cloud.githubusercontent.com/assets/26923792/25904715/55037df2-35a0-11e7-99f7-3092dbea4019.jpg)

second: I guess it is described correctly, but somehow for about 10 or 20 minutes I did not get how to write ":wq", i.e. more specific how to switch in the seperate line in the bottom (using escape, now I know).
The Problem: you describe what is to be done above the gif, and how it is done below. I did not read far enough to get to the explanation. 
solution: maybe put the explanation above the gif.

third: the gitlab server from RWTH updated their appearance, the gifs are in some part out of date, which is mostly all right, just the "Commits --> Network" is not to be found anywhere.

fourth: the "For # 1" mentioning of the issue did not work, i.e. I could not find it mentioned on the gitlab-server.

fifth: what about the branch? 
in the tutorial you merged, but still have the "issue1_text" branch in the server repo as well as on the local repo.
in the new gitlab layout you get the choice to remove the branch:
![remove branch](https://cloud.githubusercontent.com/assets/26923792/25905144/7c75e11c-35a1-11e7-81aa-791b062081fb.jpg)

I did that, and then pulled the master branch from the server.

But still I have this extra branch at my local repo. How do I delete it?
Do I have to pull (the not longer existing) branch from the server to delete the local one?

FYI: @marcusfuchs

**Comment by marcusfuchs** [comment]
@aku-cbe Perfect, thanks for your feedback! This also gives me motivation to further improve the tutorial, so I hope to get around addressing your points and some of the other open issues in the next days.

**Comment by marcusfuchs** [comment]
@aku-cbe 
Thanks again for the feedback. I'll open a pull request with my changes for you to review.

**Comment by PMehrfeld** [comment]
@aku-cbe Are all problems solved with #12? Then this issue can be closed.
