### ISSUE TITLE
TortoiseGit

### ISSUE THREAD

**Issue by PMehrfeld** [RWTH-EBC/EBC-Tutorials#13]
Just recognized the quite old branch TortoiseGit.
@fstinner: You seem to be the creator. Any updates about this branch?

**Comment by fstinner** [comment]
I have made some extensions for TortoiseGit. If not wanted, then delete branch. But I can merge it too.

Von: Philipp Mehrfeld [mailto:notifications@github.com]
Gesendet: Montag, 22. Mai 2017 15:40
An: RWTH-EBC/EBC-Tutorials <EBC-Tutorials@noreply.github.com>
Cc: Stinner, Florian <FStinner@eonerc.rwth-aachen.de>; Mention <mention@noreply.github.com>
Betreff: [RWTH-EBC/EBC-Tutorials] TortoiseGit (#13)


Just recognized the quite old branch TortoiseGit.
@fstinner<https://github.com/fstinner>: You seem to be the creator. Any updates about this branch?

**Comment by PMehrfeld** [comment]
@fstinner: We all love improvements. Therefore, I would suggest you open a pull request :)

**Comment by fstinner** [comment]
Closed
