### ISSUE TITLE
Substitute WinPython link with anaconda

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/EBC-Tutorials#16]
The WinPython link should either be substituted with an anaconda link or an anaconda link should be added as alternative. 
For Mac or Linux users (e.g. using RWTH computational cluster) WinPython is not an alternative. 
However, anaconda is plattform independent.

**Comment by PMehrfeld** [comment]
On the one hand, this might be a good option. I also use anaconda in combination with its virtual environments. We should also give students the hint with computers' and users' environment PATH variables.

On the other hand, I am not sure, whether contributors to this repository agreed to only present the institutes common solution of WinPython.

@MichaMans and @marcusfuchs: What is your opinion here?

**Comment by MichaMans** [comment]
I vote for an alternative section because in my opinion, the initial wall of "how to use python" is getting higher with anaconda usage. Nevertheless it's probably the best way to use it with the Linux cluster, if the Linux python versions are not doing properly.

**Comment by marcusfuchs** [comment]
In my experience, conda works a lot better than WinPython. So personally, I would just promote the use of conda. If other think that WinPython is a good option for their applications, I would be happy with mentioning both.

**Comment by PMehrfeld** [comment]
I added sections for Anaconda's environments and how to work with Windows' `PATH` environment variable.
