### ISSUE TITLE
Git tutorial: Path to git.exe not valid for every git version

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/EBC-Tutorials#18]
The git tutorial readme lists:

C:\Program Files (x86)\Git\bin;

as path to git.exe. However, the current software center version C:\Program Files\Git\bin;

Should be added as info to prevent confusion.

**Comment by MichaMans** [comment]
It's an e.g. so from my point of view only an example path

**Comment by PMehrfeld** [comment]
I see it the same way as @MichaMans. @JSchiefelbein: Do you think we can close this issue without any changes?

**Comment by JSchiefelbein** [comment]
Yeah, it is only an example path, but it led to confusion for those students, which are using the current software center installation. This is automatically installed into  C:\Program Files\Git. 
As I guess that mainly new students are going to be interested in GIT integration, they might run into trouble. 
Changing the example path is easy to do. However, it would be more effort to change the fancy gif animation (which should probabily stay the same).
