### ISSUE TITLE
Table of Contents at beginning

### ISSUE THREAD

**Issue by jteeonerc** [RWTH-EBC/EBC-Tutorials#4]
A Table of Contents with links to the single chapters would be useful

**Comment by marcusfuchs** [comment]
I agree. Do you want to add this, @jteeonerc ?

**Comment by jteeonerc** [comment]
I will add it during the next weeks

**Comment by PMehrfeld** [comment]
I don't know what kind of Table of Content you are aiming to implement. But one nice example can be found here: https://github.com/alexa/skill-sample-nodejs-quiz-game

**Comment by FWuellhorst** [comment]
I added two different table of contents. For EBC-Python-101 i chose images like @PMehrfeld suggested. Although this type of a table of content is prettier and more user-friendly, it generates a lot of images and is way more work. Also, if you want to change the title of a chapter, you have to make the images again.

For the EBC-Git-101 i added a conventional table of content using the link-option of markdown files. After each section i added a "go back" line to get to the top of this large readme.md 
Conventional table of contents can easily be generated by online tools or a short python-script.

If the "image" table of content is preferred for the GIT-Tutorial, i will make the necessary images and chapters for you. Vice versa for the conventional table of contents for the python-Tutorial.

**Comment by PMehrfeld** [comment]
@FWuellhorst: Thanks for this work and the two suggestions!

@jteeonerc @marcusfuchs @MichaMans @mahoffmann : Maybe you can choose between the following three options:

1. Use picture variant for both Tutorials (the nicer one)
1. Use regular table of content for both (the easier one)
1. Use them as it is in the branch and merge it into master

Here are the links to make it easier for you:
[EBC-Git-101](https://github.com/RWTH-EBC/EBC-Tutorials/tree/Issue4_TableOfContents/EBC-Git-101)
[EBC-Python-101](https://github.com/RWTH-EBC/EBC-Tutorials/tree/Issue4_TableOfContents/EBC-Python-101)

Just a quick vote for 1., 2., or 3. would be great :)

Btw. I go for 1.

**Comment by marcusfuchs** [comment]
More in favour of (2), but also fine with (3) - or even (1), if someone commits to the extra work of keeping that up to date ;)

**Comment by PMehrfeld** [comment]
Thanks @marcusfuchs for you opinion.
I would suggest to go with option 2.
@FWuellhorst: Please apply necessary changes and open a pull request.
