### ISSUE TITLE
Youtube Video Tutorials (Playlist) is a dead link

### ISSUE THREAD

**Issue by mahoffmann** [RWTH-EBC/EBC-Tutorials#40]
The mentioned video tutorials do not exist any more (that's at least what I can see)
(https://www.youtube.com/playlist?list=PLkHsKoi6eZnwpn7P5G8gEBebAY8Jbky4N)

See section "Time to say goodbye" in the Readme,   line 302
 https://github.com/RWTH-EBC/EBC-Tutorials/tree/master/EBC-Python-101#time-to-say-goodbye

**Comment by PMehrfeld** [comment]
@mahoffmann : Thanks for the hint.

I just deleted that bullet point. I think everyone can learn python without these videos ;)

If someone has objections, please reopen this issue.
