### ISSUE TITLE
EBC-Python-101 - ObjectOrientation.ipynb update

### ISSUE THREAD

**Issue by holzhauerL** [RWTH-EBC/EBC-Tutorials#44]
#### Typo
There is a mixture of English and German usage right at the start of the jupyter notebook file in the second header.

#### Pandas
pd.Series.from_csv() [deprecated](https://stackoverflow.com/questions/57313621/no-from-csv-method-in-pandas), can be replaced with pd.read_csv().

**Comment by PMehrfeld** [comment]
@lgh237 : Thanks for raising the issue!  
Do you already have a satisfying solution? Then feel free to make a pull request and assign someone of EBC as reviewer.

**Comment by holzhauerL** [comment]
Yes, i think i could fix it. I'm still pretty new to the collaborative git workflow, but i'll try a pull request and will assing you @PMehrfeld, if that's ok.

**Comment by PMehrfeld** [comment]
Alright, thanks a lot.  
I hope, our Git one-o-one tutorial helps to understand the workflow ;)   
https://github.com/RWTH-EBC/EBC-Tutorials/tree/master/EBC-Git-101

**Comment by holzhauerL** [comment]
Yes, it really helps! I think it's generally a great idea 👍 

I checked out a new branch locally called _issue44_ , where I commited my changes. Then, following the steps provided in [this section](https://github.com/RWTH-EBC/EBC-Tutorials/tree/master/EBC-Git-101#creating-a-new-branch-and-commiting-changes), I tried the command `git push origin issue44` which resulted in the following:  
`remote: Permission to RWTH-EBC/EBC-Tutorials.git denied to lgh237.  
fatal: unable to access 'https://github.com/RWTH-EBC/EBC-Tutorials.git/': The requested URL returned error: 403`  
Did I do something wrong or do I simply need the permission?

**Comment by PMehrfeld** [comment]
@lgh237: I invited you as collaborator. After confirming the invitation you should be able to push your branch.

**Comment by holzhauerL** [comment]
Thank you, now it worked. Although there are a lot more changes commited than i've consciously made. Maybe that's because of the .ipynb format of the file.
But this version works fine on my machine.

**Comment by PMehrfeld** [comment]
@lgh237 : Thanks for making the PR and sticking to the correct workflow 👍 

Anyway, @FWuellhorst will have a quick look to clean up the undesired changes due to the *.ipynb format.
