### ISSUE TITLE
Create Password and SSH

### ISSUE THREAD

**Issue by dcali** [RWTH-EBC/EBC-Tutorials#6]
Hallo,

I think it would be useful to explain SSH is not necessary. Furthermore, I believe it is important, for new users, that they have to actively generate a new password (at least this was an issue for me). 

Best
Davide

**Comment by JSchiefelbein** [comment]
Just my two cents: Depending on the repos size, cloning via https might fail (this is the case for pycity_calc and pycity_opt). In this case, SSH-usage is necessary to successfuly clone the repo.

**Comment by dcali** [comment]
Thanks Ja, I didn't know this. Do we need putty to generate our **SSH key**?

**Comment by JSchiefelbein** [comment]
If you are using TortoiseGIT (or similar), you probably need PUTTY to generate a (putty) SSH key. If you are using cmd window / git bash, you can create a SSH key pair via:
cd %HOME%
mkdir .ssh
ssh-keygen -t rsa -C "$your_email"

After that, copy the public key to github (or gitlab,respectively) 
type %userprofile%\.ssh\id_rsa.pub | clip
(to copy public key)

**Comment by mlauster** [comment]
Or by simply typing `Puttygen` into windows search bar and use PuTTygen's GUI to create your key. :)

**Comment by PMehrfeld** [comment]
I think the question is fully answered :)
