### ISSUE TITLE
Password / Login

### ISSUE THREAD

**Issue by dcali** [RWTH-EBC/EBC-Tutorials#7]
When doing operations as described in the tutorial, I have to give my username and my password almost each 3 operations. How do I avoid this?

**Comment by PRemmen** [comment]
@dcali directly after giving your username and password type:

```
git config --global credential.helper wincred
```

this works for me on different severs and repos.

**Comment by fstinner** [comment]
@dcali @PRemmen Does this also work with TortoiseGIT? 

I have tried the following:
![unbenannt](https://cloud.githubusercontent.com/assets/11679462/22335018/40126fe4-e3dd-11e6-9497-be8320047577.PNG)

**Comment by PRemmen** [comment]
sorry, i have not installed tortoiseGIT but you seem to be in the right settings section?! :)

**Comment by JSchiefelbein** [comment]
@fstinner You should be able to set an effective or local GIT user name and email within TortoiseGIT settings/GIT.

**Comment by PMehrfeld** [comment]
I think this can be closed. @fstinner Please reopen it, if further questions appear.
