### ISSUE TITLE
Idea for the tutorial

### ISSUE THREAD

**Issue by dcali** [RWTH-EBC/EBC-Tutorials#8]
The tutorial helps and is well done, but is long. I belive a __table at the end of it__, a sort of __*resume*__, containing the most important "_**keywords**_" to operate within the repos would help a lot.

**Comment by PRemmen** [comment]
Do the links in this section https://github.com/RWTH-EBC/EBC-Tutorials/tree/master/EBC-Git-101#what-next especially http://rogerdudler.github.io/git-guide/files/git_cheat_sheet.pdf help?

**Comment by dcali** [comment]
The last link is exactly what I was looking for, thank you very much!
