### ISSUE TITLE
Linking to other, more specific turorials wanted?

### ISSUE THREAD

**Issue by mahoffmann** [RWTH-EBC/EBC-Tutorials#9]
Hi,

I just found the atlassian git sites and found them to be really comprehensive - even rebasing is easy to understand ;-)
https://www.atlassian.com/git

Do we want to extend the readme or give hints to further reading?

Or other question: how to generally address those at the institute who might be interested in git topics?

**Comment by MichaMans** [comment]
Hi,
good hint, but i think we already got this link in the "What's next" section at the end of the Tutorial. We might rethink the positioning of this section. Maybe it's better to move it to the top of the Tutorial.

Adressing the "git-people" is a good question. I think a lot of these people know each other but it might be hard for someone who gets started. In this case we should always refer to this place and with the issue tracker system we should be able to improve the tutorial and maybe include some tricky parts of git. So i think this place is a good start for adressing the people interessted in git.

**Comment by mahoffmann** [comment]
already done before - sorry and closed
